---
baseURL: https://matteojoliveau.com/
languageCode: en-us
enableRobotsTXT: true
title: Matteo Joliveau
params:
  title: Matteo Joliveau
  description: Software Developer & Cloud Enthusiast
  images:
  - feature-image.png
menu:
  main:
  - url: "/about/"
    name: About Me
    weight: 3
    identifier: about
  - url: "/contacts/"
    name: Contacts
    weight: 4
  - url: "/projects/"
    name: Projects
    weight: 1
    identifier: projects
blackfriday:
  hrefTargetBlank: true
markup:
  goldmark:
    renderer:
      unsafe: true
module:
  mounts:
    - source: ./node_modules/devicon/fonts
      target: static/fonts
    - source: ./node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts