---
baseURL: https://matteojoliveau.com/
languageCode: en-us
enableRobotsTXT: true
title: Matteo Joliveau
params:
  title: Matteo Joliveau
  description: Software Developer & Cloud Enthusiast
  images:
  - feature-image.png
menu:
  main:
  - url: "/projects/"
    name: Projects
    weight: 1
    identifier: projects
  - url: "/talks/"
    name: Talks
    weight: 2
    identifier: talks
  - url: "/about/"
    name: About Me
    weight: 3
    identifier: about
  - url: "/contacts/"
    name: Contacts
    weight: 4  
  - url: "https://standardresume.co/r/matteojoliveau"
    name: Resume
    weight: 5
    params:
      external: true
      icon: fas fa-external-link-alt
blackfriday:
  hrefTargetBlank: true
markup:
  goldmark:
    renderer:
      unsafe: true
module:
  mounts:
    - source: ./static
      target: static
    - source: ./node_modules/devicon/fonts
      target: static/css/fonts
    - source: ./node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts